name: Gerar APK Automatico
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - run: npx expo prebuild --platform android --clean
      - run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: android/app/build/outputs/apk/release/app-release.apk
